permalink: /blog/:month-:day-:year-:title


markdown: redcarpet
safe: true
lsi: false
pygments: true
exclude: ["README.md"]

# prose.io stuff
prose:
  siteurl: http://sleconf.org
  media: /assets/images/
  metadata:
    _posts:
      - name: "layout"
        field: 
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          type: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Author name"
          value: ""
          placeholder: "SLE"
      - name: "authorlink"
        field:
          element: "text"
          type: "text"
          label: "Author website"
          value: ""
    2014:
      - name: "layout"
        field: 
          element: "hidden"
          value: "default2014"
      - name: "title"
        field:
          element: "text"
          type: "text"
          label: "Title"
          value: ""
