permalink: /blog/:month-:day-:year-:title

gems:
  - jekyll-redirect-from

markdown: redcarpet
safe: true
lsi: false
highlighter: pygments
exclude: ["README.md"]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# prose.io stuff
prose:
  siteurl: http://sleconf.org
  media: /assets/images/
  metadata:
    _posts:
      - name: "layout"
        field: 
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          type: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Author name"
          value: ""
          placeholder: "SLE"
      - name: "authorlink"
        field:
          element: "text"
          type: "text"
          label: "Author website"
          value: ""
    2014:
      - name: "layout"
        field: 
          element: "hidden"
          value: "default2014"
